In [2]:
import numpy as np

In [3]:
# Given a 2D list, create a numpy 2D array using it.
# Note: Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
# a = np.full((3,3),arr)
a = np.full((len(arr),len(arr[0])),arr)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1.
a = np.zeros(10,dtype=int)
a[4] = 1
# print(a)
for i in range(len(a)):
    print(a[i],end = ' ')

0 0 0 0 1 0 0 0 0 0 

In [5]:
# if we initialize it empty it gives a random value but not in randint or randfloat
a = np.random.rand()
print(a)

0.32934335283779825


In [6]:
# both included returns a number between low to high values
a = np.random.randint(4,10)
print(a)

9


In [7]:
print(np.random.randint(10,size = (3,3)))

[[0 6 6]
 [4 0 8]
 [3 0 0]]


In [8]:
# Create an array with values ranging consecutively from 9 to 49 (both inclusive).
a = np.arange(9,50,dtype=int)
print(a)

[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
# Create a matrix having diagonal elements as 1 and all other elements as 0 of size (5, 6).
a = np.eye(5,6,dtype=int)
print(a)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


In [10]:
# You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.
a = np.linspace(0,5,10)[1:9]
print(a)

[0.55555556 1.11111111 1.66666667 2.22222222 2.77777778 3.33333333
 3.88888889 4.44444444]


In [11]:
# print 11 12 13 in a given 4*5 matrix
# 9 4 19
#  11 to 20
# 7 8  12 13
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
# print(arr)

def iterate(value):
    for i in value:
        print(i,end = ' ')
    print()

def iterate1(value):
    for i in value:
        for j in i:
            print(j,end = ' ')
    print()

value = iterate(arr[2,:3])
value1 = iterate(arr[1:4,3])
value2 = iterate1(arr[2:4,0:5])
value3 = iterate1(arr[1:3,1:3])


11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 


In [12]:
# Given an integer array of size 10. Print the index of elements which are multiple of 3.
a = np.array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
for i in np.where(a%3 == 0):
    print(*i)


1 4 7


In [13]:
# Given an integer array of size 10. Replace the odd number in numpy array with -1 ?
# Note: Generate the following array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# condition
a[a%2 != 0] = -1
print(a)


[-1  2 -1  4 -1  6 -1  8 -1 10]


In [14]:
# Given an integer array of size 9 and replace the first occurrence of maximum value by 0?
# Note: Generate the following array
a = np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
a[a == max(a)] = 0
for i in range(len(a)):
    print(a[i])

11
2
13
4
15
6
0
8
19


In [15]:
# Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?
# Note: Generate the following array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
m = (arr>2) & (arr<9)
arr[m] *= -1
print(arr[m])

for i in range(len(arr)):
    print(arr[i])



[-3 -4 -5 -6 -7 -8]
1
2
-3
-4
-5
-6
-7
-8
9
10


In [16]:
# Given age and height of 20 students in two different numpy arrays with name age and height (in cms). Print the age of those students whose height is above 155 cm.
# Print the Numpy array.

age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])

# m = (height>=155)
height1 = height[height>=155]
# print(height)
age1 = np.where(height1)
# print(age)

for i in age1:
    print(*age[i], " ",*height[i])
    print(age[i])



15 17 19 20 14 21 16 19 13 20 22 23   156 144 180 162 152 157 154 155 151 150 158 179
[15 17 19 20 14 21 16 19 13 20 22 23]


In [17]:
# Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
# That means, we should re-arrange complete row based on 2nd columns' values.
# Given 2D array is:
#  [[21 20 19 18 17]
#   [16 15 14 13 12]
#   [11 10  9  8  7]
#   [ 6  5  4  3  2]]


arr = np.array([[21,20,19,18,17],[16,15,14,13,12],[11,10,9,8,7],[6,5,4,3,2]])
# for i in range(len(arr)-1):

y = arr[arr[: , 1].argsort()]
print(y)




[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


Terrorism Data

In [18]:
# Find value of killed column only where country == ‘United States’?
# Print 0 in place of missing values.
# Print count of Killed as integer value.
import csv
# data = np.loadtxt('terrorismData.csv') # this gives error because it contains column names
with open('terrorismData.csv',encoding='utf8') as file_obj:
    data = csv.DictReader(file_obj,skipinitialspace = True)
    killed = []
    country = []
    ans1 = []
    for row in data:
        killed.append(row['Killed'])
        country.append(row['Country'])


    np_killed = np.array(killed)
    np_country = np.array(country)

    np_killed[np_killed == ''] = '0.0'
    np_killed = np.array(np_killed,dtype = float)

    bool_arr = np_country == 'United States'
    # bool_arr represents if there is united states in the row
    # then it will declared as True else False
    ans = np_killed[bool_arr]
    for i in ans:
        ans1.append(int(i))

# sum ofpeoples killed in usa


print(sum(ans1))

3771


In [19]:
# Find the number of attack held between day 10 and day 20?(ignoring the year and month)(including both day)
# Print count of NumberOFAttack as integer value.
with open('terrorismData.csv',encoding='utf8') as file_obj:
    data = csv.DictReader(file_obj,skipinitialspace = True)

    day = []
    for row in data:
        day.append(row['Day'])

    np_day = np.array(day,dtype = float)
    ans = np_day[(np_day >= 10) & (np_day <= 20)]

    print(len(ans))

66330


In [20]:
# Find the number of attack held between 1 Jan 2010 and 31 Jan 2010?(including both date).
# Note Ignore the case where day is 0
# Print count of NumberOFAttack as integer value.
with open('terrorismData.csv',encoding='utf8') as file_obj:
    data = csv.DictReader(file_obj,skipinitialspace = True)

    day,month,year  = [],[],[]
    for row in data:
        day.append(row['Day'])
        month.append(row['Month'])
        year.append(row['Year'])


    np_day = np.array(day,dtype = float)
    np_month = np.array(month,dtype = float)
    np_year = np.array(year,dtype = float)

    # Didnt understand these concept
    np_day=np_day[np_month==1]
    np_year=np_year[np_month==1]
    np_day=np_day[np_year==2010]

    print(len(np_day[np_day != 0]))


271


In [21]:
# As we knew the Kargil ( in Jammu and Kashmir) War that took place between May 1999 and July 1999 (3 Months) ,so there was a huge conflict in Kashmir Valley during this period.
# In this dataset, there is no information regarding the war between the two countries to find out the casualty during the war.
# So find out the attack in this period in which maximum casualties happened.
# Print the count of casualties (as integer), city in which that attack happened and name of attack group.
# Note : Casualty = Killed + Wounded.Fill the empty value in killed or wounded feature to 0.
with open('terrorismData.csv',encoding='utf8') as file_obj:
    data = csv.DictReader(file_obj,skipinitialspace = True)

    city = []
    casualty = []
    for row in data:
        if row['State'] == 'Jammu and Kashmir' and row['Year'] == "1999":
            if row['Month'] == '5' or row['Month'] == '6' or row['Month'] == '7':
                city.append([row['City'],row['Group']])
                casualty.append([row['Killed'],row['Wounded']])  
                    
    np_city = np.array(city)
    np_casualty = np.array(casualty)

    np_casualty[np_casualty == ''] = '0.0'
    np_casualty = np.array(np_casualty,dtype = float)

    np_casualty = np.sum(np_casualty,axis=1)
    index = np.argmax(np_casualty)

    print(int(np_casualty[index]),np_city[index][0],np_city[index][1])
   

22 Kargil District Separatists


In [22]:
# Find the casualty in the Red Corridor States ? Mainly Red corridor states include Jharkhand, Odisha, Andhra Pradesh, and Chhattisgarh.
# Note: Casualty=Killed +Wounded
# Print count of Casualty as integer value.


with open('terrorismData.csv',encoding="utf8") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)
    
    casualty = []
    for row in data:
        if row['State']=='Chhattisgarh' or row['State']=='Odisha' or row['State']=='Jharkhand' or row['State']=='Andhra Pradesh':
                casualty.append([row["Killed"],row["Wounded"]])

    np_casualty = np.array(casualty)
    
    np_casualty[np_casualty==''] = "0.0"
    np_casualty = np.array(np_casualty, dtype = float)
    
    np_casualty = np.sum(np_casualty, axis=1)
    total_casualty = np.sum(np_casualty)
    print(int(total_casualty))

5628


In [23]:
# Find the most frequent day of attack in a terrorismDataset ?
# Note: Here np.unique can be used.
# Print count of frequent day and number of attack as Integer value.
with open('terrorismData.csv',encoding="utf8") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)
    
    day = []
    for row in data:
        day.append(row['Day'])
        
    np_day = np.array(day, dtype='int')
    day, count = np.unique(np_day, return_counts=True)

    index = np.argmax(count)
    print(day[index], count[index])

15 6500
